services:
  - type: web
    name: ai-realtime-dashboard
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    rootDir: server
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
